pekko {
  actor {
    provider = "cluster"
  }

  discovery {
    method = pekko-dns
  }

  cluster {
    min-nr-of-members = 1
    log-info = on
    shutdown-after-unsuccessful-join-seed-nodes = 60s

    downing-provider-class = "org.apache.pekko.cluster.sbr.SplitBrainResolverProvider"
  }

  remote {
    artery {
      transport = tcp
      canonical.hostname = "127.0.0.1"
      canonical.port = 0
    }
  }
}
