blueprint {
  streamlets {
    ingress = swissknife.pekko.DataGenerator
    pekko-process = swissknife.pekko.PekkoTransformation
    raw-egress = swissknife.pekko.PekkoLogger
    pekko-egress = swissknife.pekko.PekkoLogger
    pekko-config-output = swissknife.pekko.PekkoConfigLogger
  }

  topics {
    source-data-pipe {
      producers = [ingress.out]
      consumers = [raw-egress.in, pekko-process.in, pekko-config-output.in]
    }

    pekko-pipe {
      producers = [pekko-process.out]
      consumers = [pekko-egress.in]
    }
  }
}
